services:
  main:
    build:
      context: ./
      dockerfile: main.dockerfile
    container_name: main
    restart: always
    ports:
      - "9191:9191"
    cpuset: "0-1"
    deploy:
      resources:
        limits:
          cpus: '2.4'
          memory: 512m
        reservations:
          cpus: '1'
          memory: 256m
    networks:
      my-network:
        aliases:
          - main

  mock-lookup:
    build:
      context: ./mock-lookup
      dockerfile: mock-lookup.dockerfile
    container_name: mock-lookup
    restart: always
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
      - "8086:8086"
      - "8087:8087"
      - "8088:8088"
      - "8089:8089"
      - "8090:8090"
      - "8091:8091"
    cpuset: "2-3"
    deploy:
      resources:
        limits:
          cpus: '2.4'
          memory: 512m
        reservations:
          cpus: '1'
          memory: 256m
    networks:
      my-network:
        aliases:
          - mock-lookup



networks:
  my-network:
    driver: bridge